spring:
  application:
    name: discovery

server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    hostname: ${EUREKA_HOSTNAME:aws-prod-latest.onrender.com}
    prefer-ip-address: false
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443

logging:
  level:
    root: WARN
    "[com.netflix.eureka]": INFO
    "[com.netflix.discovery]": INFO
