server:
  port: ${DEV_SERVER_PORT:7761}

spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://${DEV_EUREKA_URL:localhost}/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
  instance:
    hostname: ${DEV_EUREKA_URL:localhost}
    prefer-ip-address: false
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    home-page-url: https://${DEV_EUREKA_URL:localhost}/
    status-page-url: https://${DEV_EUREKA_URL:localhost}/actuator/info
    health-check-url: https://${DEV_EUREKA_URL:localhost}/actuator/health


logging:
  level:
    root: INFO
    "[com.netflix.eureka]": INFO
    "[com.netflix.discovery]": INFO

