server:
  port: ${PROD_SERVER_PORT:8761}

spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${PROD_EUREKA_URL:discovery-server-prod}:8761/eureka/

  instance:
    hostname: ${PROD_EUREKA_URL:discovery-server-prod}
    prefer-ip-address: false

logging:
  level:
    root: WARN
    "[com.netflix.eureka]": INFO
    "[com.netflix.discovery]": INFO