name: Prod deployment

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: qarani/discovery-server:prod
          build-args: |
            SPRING_PROFILES_ACTIVE=prod

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
          script: |
            echo "${{ secrets.DISCOVERY_SERVER_PROD_ENV }}" > /home/ubuntu/.discovery-server-prod.env
            docker network create aws-prod-network || true
            docker pull qarani/discovery-server:latest
            docker stop discovery-server || true
            docker rm discovery-server || true
            docker run -d --name discovery-server --network aws-prod-network --env-file /home/ubuntu/.discovery-server-prod.env -p 8761:8761 qarani/discovery-server:prod




